config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "application#homepage"
  resources :pokemon_cards
  resources :user_collections
  resources :users
  get "/login", to: "sessions#login"
  post "/login", to: "sessions#process_login"
  get "/logout", to: "sessions#logout"
  get "/create", to: "users#new"
  post "/create", to: "users#create"
  # root "pokemon_cards#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon_card.rb
class PokemonCard < ApplicationRecord
    has_many :user_collections
    has_many :users, through: :user_collections
    has_many :pokemon_card_types
    has_many :types, through: :pokemon_card_types

    def pokemon_card_count
        self.users.count
    end

    def self.type?(pok_type)
        PokemonCard.where(types:pok_type)
    end
end

app/models/pokemon_card_type.rb
class PokemonCardType < ApplicationRecord
    belongs_to :pokemon_card
    belongs_to :type 
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :content, presence: true, length: { maximum: 600 }
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :pokemon_card_types
    has_many :pokemon_cards, through: :pokemon_card_types
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_collections
    has_many :pokemon_cards, through: :user_collections
    has_many :posts
    validates :name, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 4 } 
    has_secure_password
end
 

app/models/user_collection.rb
class UserCollection < ApplicationRecord
    belongs_to :user 
    belongs_to :pokemon_card 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        
        @current_user = User.find_by(id: session[:user_id])
        
    end 

    def logged_in?
        
    #     if current_user
    #         return true
    #     else
    #         false
    # end
    !!current_user
    end

def authorized
    redirect_to login_path unless logged_in?
    # if !logged_in?
    #     redirect_to login_path
    # end
end
end

app/controllers/pokemon_cards_controller.rb
class PokemonCardsController < ApplicationController
    before_action :authorized, except: [:index]
    def index
        # @pokemon_cards = PokemonCard.all
        if params[:type_ids] == 
            @pokemon_cards = PokemonCard.type?('Psychic')
        elsif params[:type_ids] == 'Grass'
            @pokemon_cards = PokemonCard.type?('Grass')
        else
            @pokemon_cards = PokemonCard.all
        end
    end

    def show
        @pokemon_card = PokemonCard.find(params[:id])  
    end

    def edit
        @pokemon_card = PokemonCard.find(params[:id])
    end

    def update
        @pokemon_card = PokemonCard.find(params[:id])
        if @pokemon_card.update(card_params)
            redirect_to pokemon_card_path(@pokemon_card.id)
        else
            render :edit
        end 
    end 

    private

    def card_params
        params.require(:pokemon_card).permit(:title, :image_url, :type_ids)
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    def index
        @posts = Post.all.order("created_at DESC")
    end

    def show
        
    end 

    def new 
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save 
            redirect_to post_path(@post.id)
        else 
            render :new
        end 
    end 

    def edit
    end 

    def update
        if @post.update(post_params)
            redirect_to post_path(@post.id)
        else 
            render :edit
        end 
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end 

    private

    def post_params
        params.require(:post).permit(:title, :content, :user_id)
    end 

    def find_post
        @post = Post.find(params[:id])
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def login
    end

    def process_login
        username = params[:name]
        @user = User.find_by(name: username)
        if @user && @user.authenticate(params[:password])
            
            session[:user_id] = @user.id
            flash[:message] = "User logged in"
           
            redirect_to user_path(@user.id)
        else 
            flash[:error] = "No user found with that name and password"
            redirect_to :login
        end 
    end 

    def logout
        session.clear
        redirect_to root_path
    end 
end

app/controllers/user_collections_controller.rb
class UserCollectionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorized, except: [:new, :create]
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
      
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            
            redirect_to login_path
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
           
            redirect_to user_path(@user.id)
           
        else
            render :edit
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy 
        redirect_to root_path
    end 

    private
    def user_params
        params.require(:user).permit(:name, :password, :location, :pokemon_card_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemon_cards_helper.rb
module PokemonCardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_collections_helper.rb
module UserCollectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/homepage.html.erb
     <h1 class="title is-1 has-text-warning has-text-centered">Welcome to PokeTrade!</h1>
    <br>
<div class="colums">
    <div >
    <h3 class="subtitle is-4 is-light has-text-light has-text-centered " >
    This is an App that allows you to show off your Pokemon Card collection and set up a trade with other users through the Trade forum!
    <br>
    To get started, please <%= link_to "Create", new_user_path %> an account or <%= link_to "Log in!", login_path %>
    </h3>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeTrade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    
  </head>
  

  <body>

  <!--<section class="hero is-fullheight">  -->

    <% unless controller_name == "sessions" && action_name == "login" %>
      
    <nav class="navbar is-dark">
        <div class="navbar-menu">
          <div class ="buttons">
  
          <%= link_to "View All Cards", pokemon_cards_path, class: "navbar-item, button is-light is-rounded" %>
          
            <% if session[:user_id] %>

               <%= link_to "Home", user_path(current_user.id), class: "navbar-item, button is-light is-rounded" %>
               <%= link_to "View All Users", users_path, class: "navbar-item, button is-light is-rounded" %> 
               <%= link_to "View Trade Forum", posts_path, class: "navbar-item, button is-light is-rounded" %> 
                <div class="navbar-end">
                  <%= link_to "Log Out", logout_path, class: "navbar-item, button is-light is-rounded is-pulled-right" %>
                </div>
            <% else %>
              <%= link_to "Homepage", root_path, class: "navbar-item, button is-light is-rounded is-pulled-right" %>
              <div class="navbar-end">
                <%= link_to "Log In", login_path, class: "navbar-item, button is-light is-rounded is-pulled-right" %>
              </div>
              
              
            <% end %> 
          </div>
    
        </div>
    </nav>
    
    <% end %>

 <div class="container is-fluid" id="main_container">
   
    <%= yield %>
   </div>
  
<!--</section> -->
  </body>
</html>

app/views/pokemon_cards/edit.html.erb
<%= form_for @pokemon_card do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
    <%= f.label :type_ids %>
    <%= f.collection_select :type_ids, Type.all, :id, :name %>
    <%= f.submit %>
<% end %>

app/views/pokemon_cards/index.html.erb
<br>

<div class="columns is-multiline is-marginless">
    <% @pokemon_cards.each do |card| %>
        <div class="column is-one-fifth is-marginless">
                <a href="/pokemon_cards/<%=card.id%>">
                    <img src="<%= card.image_url %>">
                </a>
        </div>
    <% end %>
</div>

app/views/pokemon_cards/show.html.erb
 <br><br> <div class="">
 <div class="has-text-centered">
<img src="<%=@pokemon_card.image_url%>"> <br>
</div>
<div class="info">
<div class='title is-info has-text-centered is-family-monospace'>
<%= @pokemon_card.title %> <br>
</div>
<div class="subtitle is-4 is-family-monospace">
<%= @pokemon_card.pokemon_card_count %> Users have this card in their collection:
</div>

<div class="has-text-centered">
<div class="dropdown is-hoverable">
  <div class="dropdown-trigger">
    <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
      <span>Users with this Card</span>
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </div>
  <div class="dropdown-menu" id="dropdown-menu" role="menu">
    <div class="dropdown-content">
    <% @pokemon_card.users.each do |user| %>
        <div class="subtitle is-4 has-text-centered is-family-monospace">
        <%= link_to user.name, user_path(user.id) %>
    <% end %>
    </div>
  </div>
</div>
</div>
<br>
<br>

app/views/posts/_post_form.html.erb
<div class="columns">
<div class="column text-is-white">
    <%= form_for @post, builder: BulmaFormBuilder::FormBuilder do |f| %>
        <%= f.text_field :title %><br>
        <%= f.text_area :content %><br>
        <%= f.hidden_field :user_id, value: current_user.id %>
       <div class="has-text-centered">
        <%= f.submit class: "button "%>
        </div>
    <% end %> 
</div>
</div>

app/views/posts/edit.html.erb
<%= render partial: "post_form" %>

app/views/posts/index.html.erb
<div class="columns">
<div class="column is-half is-offset-one-quarter has-text-centered">

<br>
<%= link_to "Add a New Post", new_post_path, class: "button" %>
<br>

<% content_for :page_title, "Trade Forum" %> 
    <section class="section">
        <div class="container">

            <% @posts.each do |post| %>
            
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4"><%= link_to post.title, post_path(post.id) %></p>
                    </div>
                </div>
                <div class="content">
                    By: <%= post.user.name %><br>
                    <%= post.created_at %><br>
                    <%= post.content %>  
                </div>
            </div>
            <% end %>
        </div>
    </section>
</div>
</div>

app/views/posts/new.html.erb
<%= render partial: "post_form" %>

app/views/posts/show.html.erb
<div class="has-text-centered">

<div class="card-content">
    <div class="media">
        <div class="media-content">
            <p class="title is-4"><%= @post.title %></p>
        </div>
    </div>
    <div class="content">
        By: <%= link_to @post.user.name, user_path(@post.user.id) %><br>
        <%= @post.created_at %><br>
        <%= @post.content %>  
    </div>
</div>

<br>

<% if session[:user_id] == @post.user_id %>

<%= link_to "Edit this Post", edit_post_path, class: "button" %> <br>
<%= link_to "Delete this Post", post_path(@post.id), :method => :delete, data: {confirm: "Are you sure?"}, class: "button is-danger" %>
<% end %>

</div>

app/views/users/_form.html.erb
<div class="columns">
<div class="column is-half is-offset-one-quarter">

<br> 
<%= form_for @user, builder: BulmaFormBuilder::FormBuilder  do |f| %>

<%= f.text_field :name%><br>

<%= f.password_field :password %><br>

<%= f.text_field :location %> <br>
<%= f.collection_check_boxes :pokemon_card_ids, PokemonCard.all, :id, :title %> <br>
<div class="has-text-centered">
<%= f.submit class: "button"%>
</div>
<% end %> 
</div>
</div>

app/views/users/edit.html.erb
<%= render partial: 'form' %>

app/views/users/index.html.erb
<h1 class="title has-text-warning is-1">Click a User to View Their Collection:</h1>

 <body class="has-text-centered">
  

 <div class="dropdown is-hoverable">
  <div class="dropdown-trigger">
    <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
      <span>Choose a User</span>
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </div>
  <div class="dropdown-menu" id="dropdown-menu" role="menu">
    <div class="dropdown-content">
    <%@users.each do |user| %> 
      <a href="/users/<%=user.id%>" class="dropdown-item">
       <%= user.name %>
      </a>
      <%end %>
    </div>
  </div>
</div>
</body>

app/views/users/new.html.erb
<%= render partial: 'form' %>

app/views/users/show.html.erb
<body class="has-text-centered">
<h1 class="title is-1 has-text-warning"><%= @user.name %></h1>

<div id="location" class="subtitle is-4 is-white">Location: <%= @user.location %></div>
<br>
<h2 class="subtitle is-4"> Card Collection: </h2><br>
<div class="collection">

    <div class="columns is-multiline is-marginless">
        <% @user.pokemon_cards.each do |card| %>
            <div class="column is-one-fifth">
            
                <a href="/pokemon_cards/<%=card.id%>">
                    <img src="<%= card.image_url %>">
                </a>
          
            </div>
        <% end %>
    </div> 
</div>

<h2 class="subtitle is-4"> <%= @user.name %>'s Posts in the Trade Forum: </h2>
<div class="dropdown is-hoverable">
  <div class="dropdown-trigger">
    <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
      <span>View Posts</span>
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </div>
  <div class="dropdown-menu" id="dropdown-menu" role="menu">
    <div class="dropdown-content">
    <% @user.posts.each do |post| %> 
      <a href="/posts/<%=post.id%>" class="dropdown-item">
       <%= post.title %>
      </a>
      <%end %>
    </div>
  </div>
</div>

<br><br>
<div class="actions">
    <% if @user.id == @current_user.id %>
        <%= link_to "Add a Post to the Trade Forum", new_post_path, class: "button is-info" %><br><br>
        <%= link_to "Edit Your Profile", edit_user_path, class: "button is-info" %><br>
      
    <% end %>

</div>
</body>